#:schema node_modules/wrangler/config-schema.json

name = "graphql-server"
main = "src/index.ts"
compatibility_date = "2024-05-12"
# compatibility_flags = ["nodejs_compat"]
node_compat = true

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "graphql-db"
database_id = "xxxxx-xxxx-xxxx-xxxx-xxxx"
